swagger: '2.0'

# General API Specification  

info:
  version: "v1"
  title: REST API for 'Flight Service'
  description: |
    This swagger specification Provide the definition of the Flight Service REST API 
        
host: movieapp-sitepointdemos.rhcloud.com
basePath: /api
  

# General Path Specification  

paths:
 /routes:
    get:
      summary: List all Flights  
      produces:
        - application/json 
      responses:
        200:
          description: An array with all Flights.
          schema:
            type: array
            items:
              $ref: '#/definitions/Flight'
    
   
# General Type Definition                                  
definitions:
  Flight:
    type: object
    properties:
      _id:
        type: number
        description: A unique identifier of the movie. Automatically assigned by the API when the Flights is created.
      flightNumber:
        type: string
        description: The unique order flightNumber.  
      departure:
        type: string
        description: The departure name.
      destination:
        type: string
        description: The destination name.  
        
        
        
        
        
        
        