swagger: '2.0'

# General API Specification  

info:
  version: "v1"
  title: REST API for 'Route Service'
  description: |
    This swagger specification provides the definition of the Route Service REST API 
        
host: movieapp-sitepointdemos.rhcloud.com
basePath: /
  

# General Path Specification  

paths:
 /routes-gen:
    get:
      summary: List all routes  
      produces:
        - application/json 
      responses:
        200:
          description: An array with all routes.
          schema:
            type: array
            items:
              $ref: '#/definitions/RouteGen'
    
   
# General Type Definition                                  
definitions:
  RouteGen:
    type: object
    properties:
      _id:
        type: number
        description: A unique identifier of the route. Automatically assigned by the API when the route is created.
      flightNumber:
        type: string
        description: The unique order flightNumber.  
      departure:
        type: string
        description: The departure name.
      destination:
        type: string
        description: The destination name.  
        
        
        
        
        
        
        